In [1]:
import pandas as pd
import yfinance as yf

In [2]:
sp500url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
data_table = pd.read_html(sp500url)

In [3]:
tickers = data_table[0]['Symbol'].tolist()
tickers

['MMM',
 'AOS',
 'ABT',
 'ABBV',
 'ACN',
 'ADBE',
 'AMD',
 'AES',
 'AFL',
 'A',
 'APD',
 'ABNB',
 'AKAM',
 'ALB',
 'ARE',
 'ALGN',
 'ALLE',
 'LNT',
 'ALL',
 'GOOGL',
 'GOOG',
 'MO',
 'AMZN',
 'AMCR',
 'AEE',
 'AAL',
 'AEP',
 'AXP',
 'AIG',
 'AMT',
 'AWK',
 'AMP',
 'AME',
 'AMGN',
 'APH',
 'ADI',
 'ANSS',
 'AON',
 'APA',
 'AAPL',
 'AMAT',
 'APTV',
 'ACGL',
 'ADM',
 'ANET',
 'AJG',
 'AIZ',
 'T',
 'ATO',
 'ADSK',
 'ADP',
 'AZO',
 'AVB',
 'AVY',
 'AXON',
 'BKR',
 'BALL',
 'BAC',
 'BK',
 'BBWI',
 'BAX',
 'BDX',
 'BRK.B',
 'BBY',
 'BIO',
 'TECH',
 'BIIB',
 'BLK',
 'BX',
 'BA',
 'BKNG',
 'BWA',
 'BXP',
 'BSX',
 'BMY',
 'AVGO',
 'BR',
 'BRO',
 'BF.B',
 'BLDR',
 'BG',
 'CDNS',
 'CZR',
 'CPT',
 'CPB',
 'COF',
 'CAH',
 'KMX',
 'CCL',
 'CARR',
 'CTLT',
 'CAT',
 'CBOE',
 'CBRE',
 'CDW',
 'CE',
 'COR',
 'CNC',
 'CNP',
 'CF',
 'CHRW',
 'CRL',
 'SCHW',
 'CHTR',
 'CVX',
 'CMG',
 'CB',
 'CHD',
 'CI',
 'CINF',
 'CTAS',
 'CSCO',
 'C',
 'CFG',
 'CLX',
 'CME',
 'CMS',
 'KO',
 'CTSH',
 'CL',
 'CMCSA',
 'CMA',
 'CAG',
 'COP',
 'ED',
 'STZ',
 'CEG',
 'COO',
 'CPRT',
 'GLW',
 'CPAY',
 'CTVA',
 'CSGP',
 'COST',
 'CTRA',
 'CCI',
 'CSX',
 'CMI',
 'CVS',
 'DHR',
 'DRI',
 'DVA',
 'DAY',
 'DECK',
 'DE',
 'DAL',
 'DVN',
 'DXCM',
 'FANG',
 'DLR',
 'DFS',
 'DG',
 'DLTR',
 'D',
 'DPZ',
 'DOV',
 'DOW',
 'DHI',
 'DTE',
 'DUK',
 'DD',
 'EMN',
 'ETN',
 'EBAY',
 'ECL',
 'EIX',
 'EW',
 'EA',
 'ELV',
 'LLY',
 'EMR',
 'ENPH',
 'ETR',
 'EOG',
 'EPAM',
 'EQT',
 'EFX',
 'EQIX',
 'EQR',
 'ESS',
 'EL',
 'ETSY',
 'EG',
 'EVRG',
 'ES',
 'EXC',
 'EXPE',
 'EXPD',
 'EXR',
 'XOM',
 'FFIV',
 'FDS',
 'FICO',
 'FAST',
 'FRT',
 'FDX',
 'FIS',
 'FITB',
 'FSLR',
 'FE',
 'FI',
 'FMC',
 'F',
 'FTNT',
 'FTV',
 'FOXA',
 'FOX',
 'BEN',
 'FCX',
 'GRMN',
 'IT',
 'GE',
 'GEHC',
 'GEV',
 'GEN',
 'GNRC',
 'GD',
 'GIS',
 'GM',
 'GPC',
 'GILD',
 'GPN',
 'GL',
 'GS',
 'HAL',
 'HIG',
 'HAS',
 'HCA',
 'DOC',
 'HSIC',
 'HSY',
 'HES',
 'HPE',
 'HLT',
 'HOLX',
 'HD',
 'HON',
 'HRL',
 'HST',
 'HWM',
 'HPQ',
 'HUBB',
 'HUM',
 'HBAN',
 'HII',
 'IBM',
 'IEX',
 'IDXX',
 'ITW',
 'ILMN',
 'INCY',
 'IR',
 'PODD',
 'INTC',
 'ICE',
 'IFF',
 'IP',
 'IPG',
 'INTU',
 'ISRG',
 'IVZ',
 'INVH',
 'IQV',
 'IRM',
 'JBHT',
 'JBL',
 'JKHY',
 'J',
 'JNJ',
 'JCI',
 'JPM',
 'JNPR',
 'K',
 'KVUE',
 'KDP',
 'KEY',
 'KEYS',
 'KMB',
 'KIM',
 'KMI',
 'KLAC',
 'KHC',
 'KR',
 'LHX',
 'LH',
 'LRCX',
 'LW',
 'LVS',
 'LDOS',
 'LEN',
 'LIN',
 'LYV',
 'LKQ',
 'LMT',
 'L',
 'LOW',
 'LULU',
 'LYB',
 'MTB',
 'MRO',
 'MPC',
 'MKTX',
 'MAR',
 'MMC',
 'MLM',
 'MAS',
 'MA',
 'MTCH',
 'MKC',
 'MCD',
 'MCK',
 'MDT',
 'MRK',
 'META',
 'MET',
 'MTD',
 'MGM',
 'MCHP',
 'MU',
 'MSFT',
 'MAA',
 'MRNA',
 'MHK',
 'MOH',
 'TAP',
 'MDLZ',
 'MPWR',
 'MNST',
 'MCO',
 'MS',
 'MOS',
 'MSI',
 'MSCI',
 'NDAQ',
 'NTAP',
 'NFLX',
 'NEM',
 'NWSA',
 'NWS',
 'NEE',
 'NKE',
 'NI',
 'NDSN',
 'NSC',
 'NTRS',
 'NOC',
 'NCLH',
 'NRG',
 'NUE',
 'NVDA',
 'NVR',
 'NXPI',
 'ORLY',
 'OXY',
 'ODFL',
 'OMC',
 'ON',
 'OKE',
 'ORCL',
 'OTIS',
 'PCAR',
 'PKG',
 'PANW',
 'PARA',
 'PH',
 'PAYX',
 'PAYC',
 'PYPL',
 'PNR',
 'PEP',
 'PFE',
 'PCG',
 'PM',
 'PSX',
 'PNW',
 'PNC',
 'POOL',
 'PPG',
 'PPL',
 'PFG',
 'PG',
 'PGR',
 'PLD',
 'PRU',
 'PEG',
 'PTC',
 'PSA',
 'PHM',
 'QRVO',
 'PWR',
 'QCOM',
 'DGX',
 'RL',
 'RJF',
 'RTX',
 'O',
 'REG',
 'REGN',
 'RF',
 'RSG',
 'RMD',
 'RVTY',
 'RHI',
 'ROK',
 'ROL',
 'ROP',
 'ROST',
 'RCL',
 'SPGI',
 'CRM',
 'SBAC',
 'SLB',
 'STX',
 'SRE',
 'NOW',
 'SHW',
 'SPG',
 'SWKS',
 'SJM',
 'SNA',
 'SOLV',
 'SO',
 'LUV',
 'SWK',
 'SBUX',
 'STT',
 'STLD',
 'STE',
 'SYK',
 'SMCI',
 'SYF',
 'SNPS',
 'SYY',
 'TMUS',
 'TROW',
 'TTWO',
 'TPR',
 'TRGP',
 'TGT',
 'TEL',
 'TDY',
 'TFX',
 'TER',
 'TSLA',
 'TXN',
 'TXT',
 'TMO',
 'TJX',
 'TSCO',
 'TT',
 'TDG',
 'TRV',
 'TRMB',
 'TFC',
 'TYL',
 'TSN',
 'USB',
 'UBER',
 'UDR',
 'ULTA',
 'UNP',
 'UAL',
 'UPS',
 'URI',
 'UNH',
 'UHS',
 'VLO',
 'VTR',
 'VLTO',
 'VRSN',
 'VRSK',
 'VZ',
 'VRTX',
 'VTRS',
 'VICI',
 'V',
 'VST',
 'VMC',
 'WRB',
 'GWW',
 'WAB',
 'WBA',
 'WMT',
 'DIS',
 'WBD',
 'WM',
 'WAT',
 'WEC',
 'WFC',
 'WELL',
 'WST',
 'WDC',
 'WRK',
 'WY',
 'WMB',
 'WTW',
 'WYNN',
 'XEL',
 'XYL',
 'YUM',
 'ZBRA',
 'ZBH',
 'ZTS']

In [4]:
for i in range(len(tickers)):
    if tickers[i] == 'BF.B':
        tickers[i] = 'BF-B'
    elif tickers[i] == 'BRK.B':
        tickers[i] = 'BRK-B'

In [11]:
tickers_100 = tickers[:100]

In [12]:
snp_prices = yf.download(tickers_100, start='2014-05-01', end='2024-05-01')

[*********************100%%**********************]  100 of 100 completed

In [13]:
snp_prices

Price        Adj Close                                                 \
Ticker               A        AAL        AAPL        ABBV        ABNB
Date
2014-05-01   35.818916  34.306362   18.581394   34.193996         NaN
2014-05-02   35.864937  34.400631   18.615955   33.909107         NaN
2014-05-05   36.384430  34.504345   18.879208   34.028370         NaN
2014-05-06   36.174007  34.570328   18.673443   33.730206         NaN
2014-05-07   36.187153  35.088837   18.608089   34.975796         NaN
...                ...        ...         ...         ...         ...
2024-04-24  137.490005  13.920000  168.791061  167.800003  162.839996
2024-04-25  136.369995  14.130000  169.659882  167.289993  163.009995
2024-04-26  137.740005  13.880000  169.070679  159.619995  164.229996
2024-04-29  139.589996  13.980000  173.264984  161.520004  162.250000
2024-04-30  137.039993  13.510000  170.099289  162.639999  158.570007

Price                                                                  ...  \
Ticker             ABT       ACGL         ACN        ADBE         ADI  ...
Date                                                                   ...
2014-05-01   31.938892  19.190001   67.342628   62.590000   40.887089  ...
2014-05-02   31.848043  19.023333   66.937767   61.560001   41.361774  ...
2014-05-05   32.079304  18.980000   66.634125   61.439999   41.176723  ...
2014-05-06   31.864561  18.913334   66.406380   59.439999   40.822716  ...
2014-05-07   31.955420  19.073334   65.967789   58.630001   40.871006  ...
...                ...        ...         ...         ...         ...  ...
2024-04-24  106.889999  93.190002  313.540009  477.119995  196.500000  ...
2024-04-25  106.860001  93.050003  309.000000  473.440002  197.940002  ...
2024-04-26  107.529999  90.900002  308.010010  477.559998  201.970001  ...
2024-04-29  107.269997  91.250000  303.160004  473.070007  203.899994  ...
2024-04-30  105.970001  93.540001  300.910004  462.829987  200.610001  ...

Price          Volume                                                   \
Ticker           CTLT        CZR      GOOG     GOOGL      KMX      LNT
Date
2014-05-01        NaN        NaN  38110345  40086000  1744300  1588000
2014-05-02        NaN        NaN  33770463  35616000  1127200  1618200
2014-05-05        NaN        NaN  20482080  24568000  1180700  1493800
2014-05-06        NaN        NaN  33780490  36700000  2938200  1378400
2014-05-07        NaN        NaN  64486563  61486000  2787200  1265600
...               ...        ...       ...       ...      ...      ...
2024-04-24  2031700.0  3323700.0  19485700  22779100  2882600  1336200
2024-04-25  1903200.0  3162800.0  36197800  57109700  2809800  1312200
2024-04-26  2846400.0  6268500.0  56500800  64665300  2625800  1661200
2024-04-29  1470400.0  4533100.0  35914600  45610000  1673600  1661600
2024-04-30  1543200.0  7332300.0  29420800  33562900  2072800  2294700

Price
Ticker           MMM        MO         T     TECH
Date
2014-05-01   4780890  11871300  36856718   887600
2014-05-02   6887166   7622200  21109062  1409200
2014-05-05   3242236   5746500  21102839  1788000
2014-05-06   2750441   4302500  28449715  2263200
2014-05-07   2677246   7257300  26833508   981200
...              ...       ...       ...      ...
2024-04-24   3813400  12938200  74197800   984800
2024-04-25   2954800  14924200  46680400   965800
2024-04-26   4520900  13794300  37852700   973800
2024-04-29   4905000   8627100  42383300  1604600
2024-04-30  16731900  11816800  31822800  1329600

[2517 rows x 600 columns]

In [16]:
snp_prices.to_csv('snp100_prices_10yrs.csv')

In [15]:
# import zipfile

# def compress_csv_zip(input_file, output_zip):
#     with zipfile.ZipFile(output_zip, 'w', zipfile.ZIP_DEFLATED) as zf:
#         zf.write(input_file, arcname=input_file)

# # Example usage
# compress_csv_zip('snp_prices_10yrs.csv', 'snp_prices_10yrs.zip')